"""Auto-proposal: turn an optimizer sweep into a reviewable config-change PR.

The scheduled half of the build -> measure -> optimize -> repeat loop, WITHOUT removing
the human. It runs the walk-forward optimizer, and only when a swept config beats the
incumbent on a *trusted, out-of-sample* basis does it propose changing the live
``max_extension_atr`` default -- by editing ``config.py`` and emitting a PR title/body for a
GitHub Actions workflow to open. A human still reviews and merges the PR; nothing
auto-deploys. Conservative by design: a thin or in-sample-only edge proposes nothing, so the
loop never spams overfit changes.
"""

import argparse
import logging
import re
from dataclasses import dataclass
from pathlib import Path

from swing_screener.analytics.performance import MIN_LEADERBOARD_N
from swing_screener.config import StrategyConfig
from swing_screener.pipeline.optimize import OptimizeResult, fetch_daily, optimize
from swing_screener.pipeline.replay import format_leaderboard

log = logging.getLogger(__name__)

# Default source of the live gate default (relative to the repo root the job checks out).
_CONFIG_PATH = Path("src/swing_screener/config.py")
_GATE_RE = re.compile(r"(max_extension_atr:\s*float\s*=\s*)[0-9.]+")


@dataclass(frozen=True)
class Proposal:
    knob: str           # the StrategyConfig field to change (currently always the gate)
    current: float
    proposed: float
    title: str
    body: str


def _incumbent_name(base_cfg: StrategyConfig) -> str:
    """The grid name for the currently-shipped gate (matches build_config_grid's format)."""
    return f"ext_{base_cfg.max_extension_atr:.1f}"


def propose(
    result: OptimizeResult,
    base_cfg: StrategyConfig,
    *,
    min_oos_trades: int = MIN_LEADERBOARD_N,
) -> Proposal | None:
    """Propose a gate change iff a swept config genuinely beats the incumbent.

    Guards (all must hold, or nothing is proposed):
      * there is an in-sample winner, and it is NOT already the incumbent;
      * the winner has a TRUSTED out-of-sample sample (``n_closed >= min_oos_trades``);
      * its out-of-sample lower 95% bound is positive (a real edge, not noise); and
      * its out-of-sample expectancy beats the incumbent's.
    The out-of-sample gates are the anti-overfit teeth: an edge that only shows up
    in-sample never makes it into a PR.
    """
    winner = result.winner
    if winner is None or winner == _incumbent_name(base_cfg):
        return None

    w_oos = result.out_of_sample.get(winner)
    if w_oos is None or w_oos.n_closed < min_oos_trades or w_oos.expectancy_ci_low <= 0:
        return None

    inc_oos = result.out_of_sample.get(_incumbent_name(base_cfg))
    inc_oos_expectancy = inc_oos.expectancy_r if inc_oos is not None else 0.0
    if w_oos.expectancy_r <= inc_oos_expectancy:
        return None

    proposed = float(winner.removeprefix("ext_"))
    title = (f"optimizer: propose max_extension_atr "
             f"{base_cfg.max_extension_atr} → {proposed}")
    body = (
        "Auto-generated by the scheduled optimizer (`pipeline.propose`). **Review before "
        "merging** — nothing is applied without your approval.\n\n"
        f"A walk-forward sweep finds `max_extension_atr={proposed}` beats the incumbent "
        f"`{base_cfg.max_extension_atr}` on a held-out, out-of-sample basis "
        f"(expectancy {w_oos.expectancy_r:.2f}R, 95% low {w_oos.expectancy_ci_low:.2f}, "
        f"n={w_oos.n_closed}).\n\n"
        "### In-sample leaderboard\n```\n" + format_leaderboard(result.in_sample) + "\n```\n"
        "### Out-of-sample leaderboard\n```\n" + format_leaderboard(result.out_of_sample) + "\n```\n"
    )
    return Proposal(knob="max_extension_atr", current=base_cfg.max_extension_atr,
                    proposed=proposed, title=title, body=body)


def apply_to_config(source: str, proposal: Proposal) -> str:
    """Return ``config.py`` source with the gate default set to ``proposal.proposed``.

    Replaces only the ``max_extension_atr`` default literal (first match); raises if the
    field isn't found, so a refactor that moved/renamed it fails loudly instead of silently
    producing an empty diff.
    """
    new, n = _GATE_RE.subn(rf"\g<1>{proposal.proposed}", source, count=1)
    if n == 0:
        raise ValueError("max_extension_atr default not found in config source")
    return new


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Sweep configs over daily history and, if one beats the incumbent "
                    "out-of-sample, edit config.py + emit a PR title/body.")
    parser.add_argument("--tickers", required=True, help="comma-separated")
    parser.add_argument("--cache-dir", type=Path, default=Path(".cache"))
    parser.add_argument("--config-path", type=Path, default=_CONFIG_PATH)
    parser.add_argument("--out-dir", type=Path, default=Path("."))
    parser.add_argument("--oos-frac", type=float, default=0.3)
    parser.add_argument("--min-oos-trades", type=int, default=MIN_LEADERBOARD_N)
    args = parser.parse_args()
    logging.basicConfig(level=logging.INFO)

    tickers = [t.strip().upper() for t in args.tickers.split(",") if t.strip()]
    frames = fetch_daily(tickers, args.cache_dir)
    if not frames:
        log.error("no data fetched for %s; proposing nothing", tickers)
        return

    result = optimize(frames, timeframe="1d", oos_frac=args.oos_frac)
    proposal = propose(result, StrategyConfig(), min_oos_trades=args.min_oos_trades)
    if proposal is None:
        log.info("no config change proposed (no trusted out-of-sample winner over incumbent)")
        return

    args.config_path.write_text(apply_to_config(args.config_path.read_text(encoding="utf-8"),
                                                proposal), encoding="utf-8")
    (args.out_dir / "pr_title.txt").write_text(proposal.title, encoding="utf-8")
    (args.out_dir / "pr_body.md").write_text(proposal.body, encoding="utf-8")
    log.info("proposed: %s", proposal.title)


if __name__ == "__main__":
    main()
