"""initial schema

Revision ID: 16c775043cc8
Revises: 
Create Date: 2026-06-14 19:00:48.841771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16c775043cc8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('subject', sa.String(length=256), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=True),
    sa.Column('alert_key', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'run_date', 'alert_key', name='uq_email_log_dedup')
    )
    op.create_table('exit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('is_paper', sa.Boolean(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=True),
    sa.Column('tier', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('message', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('timeframe', sa.String(length=32), nullable=False),
    sa.Column('horizon', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('mtf_aligned', sa.Boolean(), nullable=False),
    sa.Column('quality_tier', sa.String(length=32), nullable=False),
    sa.Column('volatility_tier', sa.String(length=32), nullable=False),
    sa.Column('oversold', sa.Boolean(), nullable=False),
    sa.Column('trigger_close', sa.Float(), nullable=False),
    sa.Column('atr', sa.Float(), nullable=False),
    sa.Column('rsi', sa.Float(), nullable=False),
    sa.Column('entry_floor', sa.Float(), nullable=False),
    sa.Column('entry_ceiling', sa.Float(), nullable=False),
    sa.Column('stop', sa.Float(), nullable=False),
    sa.Column('target', sa.Float(), nullable=False),
    sa.Column('chart_path', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_ticker'), 'signals', ['ticker'], unique=False)
    op.create_table('universe',
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('exchange', sa.String(length=32), nullable=False),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('avg_dollar_volume', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('paper_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('timeframe', sa.String(length=32), nullable=False),
    sa.Column('horizon', sa.String(length=32), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('signal_score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('mtf_aligned', sa.Boolean(), nullable=False),
    sa.Column('quality_tier', sa.String(length=32), nullable=False),
    sa.Column('volatility_tier', sa.String(length=32), nullable=False),
    sa.Column('oversold', sa.Boolean(), nullable=False),
    sa.Column('fill_status', sa.String(length=32), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('opened_date', sa.Date(), nullable=True),
    sa.Column('last_advanced', sa.Date(), nullable=True),
    sa.Column('stop', sa.Float(), nullable=False),
    sa.Column('target', sa.Float(), nullable=False),
    sa.Column('risk', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(length=32), nullable=True),
    sa.Column('realized_r', sa.Float(), nullable=True),
    sa.Column('hold_bars', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_trades_ticker'), 'paper_trades', ['ticker'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('timeframe', sa.String(length=32), nullable=False),
    sa.Column('horizon', sa.String(length=32), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('stop', sa.Float(), nullable=False),
    sa.Column('target', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.String(length=256), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_ticker'), 'trades', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_ticker'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_paper_trades_ticker'), table_name='paper_trades')
    op.drop_table('paper_trades')
    op.drop_table('universe')
    op.drop_index(op.f('ix_signals_ticker'), table_name='signals')
    op.drop_table('signals')
    op.drop_table('exit_events')
    op.drop_table('email_log')
    # ### end Alembic commands ###
